# -*- coding: utf-8 -*-
"""medassist_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPAqxO8ZZZhZRBrCQkN_Qo-d34DJ4WmT

## **MedAssist AI — Healthcare Triage & Information Bot**
### NeuralEdge | FlowZint AI Hackathon 2026
**Name:** Aila Nasir

A support chatbot that takes user symptoms, predicts likely conditions using a trained ML model,
and explains results conversationally with safety disclaimers.

### **Install Required Libraries**
"""

!pip install google-generativeai gradio --quiet

"""### **Upload Dataset files**"""

from google.colab import files
uploaded = files.upload()

"""## **Step 1: Load and Explore the Dataset**
132 symptoms, 42 diseases. Check shape and class distribution before training.

## Load data
"""

import pandas as pd
import numpy as np

train_data = pd.read_csv('Training.csv')
test_data = pd.read_csv('Testing.csv')

print("Training shape:", train_data.shape)
print("Testing shape:", test_data.shape)

train_data.head()

"""## Check Disease Categories"""

print("Number of unique diseases:", train_data['prognosis'].nunique())
print(train_data['prognosis'].value_counts())

"""## **Step 2: Train Multi-Class Disease Prediction Model**
132 binary symptoms as features, predicting one of 41 diseases.

## Prepare features
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder

# Remove junk unnamed column if present (CSV formatting artifact)
if 'Unnamed: 133' in train_data.columns:
    train_data = train_data.drop('Unnamed: 133', axis=1)

X = train_data.drop('prognosis', axis=1)
y = train_data['prognosis']

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print("Number of features:", X.shape[1])
print("Number of classes:", len(label_encoder.classes_))

"""## Train and cross Validate"""

model = RandomForestClassifier(n_estimators=200, random_state=42)

cv_scores = cross_val_score(model, X, y_encoded, cv=5)
print("Cross-Validation Accuracy:", cv_scores.mean())

model.fit(X, y_encoded)
print("Model trained on full dataset.")

"""## Test on Held-Out Test Set"""

X_test = test_data.drop('prognosis', axis=1)
y_test = test_data['prognosis']
y_test_encoded = label_encoder.transform(y_test)

test_preds = model.predict(X_test)
test_accuracy = (test_preds == y_test_encoded).mean()

print("Test Set Accuracy:", test_accuracy)

"""#  **Step 3: Get List of Symptom Names**
### Needed to build the Gradio checkbox interface.

## Symptom list
"""

symptom_list = list(X.columns)
print("Total symptoms available:", len(symptom_list))
print(symptom_list[:10])  # preview first 10

"""## **Step 4: Configure Gemini API**
### Used to turn the raw model prediction into a natural, human-readable explanation.

## Configure Gemini
"""

import google.generativeai as genai
from google.colab import userdata

GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
genai.configure(api_key=GEMINI_API_KEY)

gemini_model = genai.GenerativeModel('gemini-2.5-flash')

response = gemini_model.generate_content("Say hello in one short sentence.")
print(response.text)

"""# **Step 5: Build the Prediction + Explanation Function**
### Combines the trained ML model (structured prediction) with Gemini
### (natural language explanation) and adds safety disclaimers.

### **Define red-flag emergency symptoms**
"""

EMERGENCY_SYMPTOMS = [
    'chest_pain', 'breathlessness', 'coma', 'blood_in_sputum',
    'bleeding', 'unconsciousness'
]

def check_emergency(selected_symptoms):
    """Check if any selected symptom is a red-flag emergency symptom."""
    for symptom in selected_symptoms:
        if symptom in EMERGENCY_SYMPTOMS:
            return True
    return False

"""## **Main prediction function**

### Gradio app
"""

SYMPTOM_EMOJIS = {
    'itching': '🤲', 'skin_rash': '🔴', 'continuous_sneezing': '🤧',
    'shivering': '🥶', 'chills': '🥶', 'joint_pain': '🦴',
    'stomach_pain': '🤢', 'acidity': '🔥', 'vomiting': '🤮',
    'fatigue': '😴', 'weight_gain': '⚖️', 'anxiety': '😰',
    'weight_loss': '📉', 'restlessness': '😣', 'lethargy': '😪',
    'cough': '😷', 'high_fever': '🌡️', 'breathlessness': '🫁',
    'sweating': '💦', 'headache': '🤕', 'chest_pain': '❤️‍🩹',
    'dizziness': '😵', 'nausea': '🤢', 'loss_of_appetite': '🍽️',
    'mild_fever': '🌡️', 'yellowish_skin': '🟡', 'dark_urine': '🟤',
    'abdominal_pain': '🤰', 'diarrhoea': '🚽', 'mucoid_sputum': '😷',
    'blurred_and_distorted_vision': '👁️', 'muscle_pain': '💪',
    'red_spots_over_body': '🔴', 'back_pain': '🔙', 'constipation': '🚫',
}

def format_symptom_label(symptom):
    emoji = SYMPTOM_EMOJIS.get(symptom, '🩹')
    clean_name = symptom.replace('_', ' ').title()
    return f"{emoji} {clean_name}"

symptom_display_map = {format_symptom_label(s): s for s in symptom_list}
symptom_display_choices = list(symptom_display_map.keys())

def get_severity_badge(confidence, is_emergency):
    if is_emergency:
        return "🔴 High Risk", "#DC2626", "#FEF2F2"
    elif confidence >= 75:
        return "🟢 Low Risk", "#16A34A", "#F0FDF4"
    elif confidence >= 50:
        return "🟡 Moderate Risk", "#D97706", "#FFFBEB"
    else:
        return "🟡 Uncertain — Monitor", "#D97706", "#FFFBEB"

def confidence_bar_html(confidence):
    filled = int(confidence // 10)
    empty = 10 - filled
    return "█" * filled + "░" * empty

!pip install reportlab --quiet

import gradio as gr
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT

TEAL = HexColor("#0F766E")
DARK = HexColor("#1A2E2A")
GREY = HexColor("#64748B")
LIGHT_BG = HexColor("#F8FAFC")

def build_pdf_report(name, age, gender, duration, conditions_text, symptoms_text,
                      predicted_disease, confidence, severity_label, explanation, filename):
    doc = SimpleDocTemplate(filename, pagesize=letter,
                             topMargin=0.6*inch, bottomMargin=0.6*inch,
                             leftMargin=0.7*inch, rightMargin=0.7*inch)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle('TitleStyle', parent=styles['Title'],
                                  fontSize=20, textColor=TEAL, alignment=TA_LEFT,
                                  spaceAfter=2, fontName='Helvetica-Bold')
    subtitle_style = ParagraphStyle('SubtitleStyle', parent=styles['Normal'],
                                     fontSize=10, textColor=GREY, spaceAfter=14)
    section_style = ParagraphStyle('SectionStyle', parent=styles['Heading2'],
                                    fontSize=12, textColor=DARK, spaceBefore=14,
                                    spaceAfter=6, fontName='Helvetica-Bold')
    body_style = ParagraphStyle('BodyStyle', parent=styles['Normal'],
                                 fontSize=10.5, textColor=DARK, leading=16)
    disclaimer_style = ParagraphStyle('DisclaimerStyle', parent=styles['Normal'],
                                       fontSize=8.5, textColor=GREY, leading=13,
                                       borderColor=GREY, borderWidth=0.5,
                                       borderPadding=10, backColor=LIGHT_BG)

    story.append(Paragraph("MedAssist AI", title_style))
    story.append(Paragraph("Healthcare Triage &amp; Information Assessment Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.2, color=TEAL, spaceAfter=14))

    timestamp = datetime.now().strftime('%B %d, %Y at %H:%M')
    story.append(Paragraph(f"<b>Report Generated:</b> {timestamp}", body_style))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Patient Details", section_style))
    display_name = name.strip() if name and name.strip() else "Not Provided"
    patient_data = [
        ["Name", display_name],
        ["Age", f"{age} years"],
        ["Gender", gender],
        ["Symptom Duration", duration],
        ["Existing Conditions", conditions_text],
    ]
    patient_table = Table(patient_data, colWidths=[2*inch, 4*inch])
    patient_table.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('FONTNAME', (1,0), (1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('TEXTCOLOR', (0,0), (-1,-1), DARK),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('LINEBELOW', (0,0), (-1,-2), 0.5, HexColor("#E2E8F0")),
    ]))
    story.append(patient_table)
    story.append(Spacer(1, 8))

    story.append(Paragraph("Reported Symptoms", section_style))
    story.append(Paragraph(symptoms_text, body_style))
    story.append(Spacer(1, 8))

    story.append(Paragraph("Assessment Summary", section_style))
    assessment_data = [
        ["Possible Condition", predicted_disease],
        ["Model Confidence", f"{confidence:.1f}%"],
        ["Risk Level", severity_label],
    ]
    assessment_table = Table(assessment_data, colWidths=[2*inch, 4*inch])
    assessment_table.setStyle(TableStyle([
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('FONTNAME', (1,0), (1,-1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 10.5),
        ('TEXTCOLOR', (0,0), (0,-1), DARK),
        ('TEXTCOLOR', (1,0), (1,-1), TEAL),
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_BG),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 10),
        ('BOX', (0,0), (-1,-1), 0.75, HexColor("#E2E8F0")),
        ('LINEBELOW', (0,0), (-1,-2), 0.5, HexColor("#E2E8F0")),
    ]))
    story.append(assessment_table)
    story.append(Spacer(1, 10))

    story.append(Paragraph("Clinical Notes &amp; Recommendations", section_style))
    explanation_clean = explanation.replace('\n', '<br/>')
    story.append(Paragraph(explanation_clean, body_style))
    story.append(Spacer(1, 16))

    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#E2E8F0"), spaceAfter=10))
    disclaimer_text = ("<b>Important Disclaimer:</b> This report was generated by an AI-based information tool "
                        "and does not constitute a medical diagnosis. The assessment is based on a machine "
                        "learning model trained on symptom-disease patterns and should not replace professional "
                        "medical evaluation. Please consult a licensed healthcare provider for accurate diagnosis "
                        "and treatment.")
    story.append(Paragraph(disclaimer_text, disclaimer_style))
    story.append(Spacer(1, 10))
    story.append(Paragraph("Generated by MedAssist AI &nbsp;|&nbsp; Healthcare Information Assessment System &nbsp;|&nbsp; NeuraMinds",
                            ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=GREY, alignment=TA_CENTER)))

    doc.build(story)


def predict_disease_v5(name, age, gender, duration, existing_conditions, selected_display_symptoms):
    if not selected_display_symptoms:
        empty_msg = """<div style='text-align:center; padding:40px; color:#94A3B8;'>
        <div style='font-size:48px; margin-bottom:12px;'>🩺</div>
        <p style='font-size:1.1rem;'>Select your symptoms to get started</p>
        </div>"""
        return empty_msg, None

    selected_symptoms = [symptom_display_map[s] for s in selected_display_symptoms]

    input_vector = pd.DataFrame([np.zeros(len(symptom_list))], columns=symptom_list)
    for symptom in selected_symptoms:
        if symptom in input_vector.columns:
            input_vector[symptom] = 1

    prediction_encoded = model.predict(input_vector)[0]
    probabilities = model.predict_proba(input_vector)[0]
    confidence = probabilities[prediction_encoded] * 100
    predicted_disease = label_encoder.inverse_transform([prediction_encoded])[0]

    is_emergency = check_emergency(selected_symptoms)
    severity_label, severity_color, severity_bg = get_severity_badge(confidence, is_emergency)

    symptoms_text = ", ".join([s.replace('_', ' ') for s in selected_symptoms])
    display_name = name.strip() if name and name.strip() else "Patient"
    conditions_text = ", ".join(existing_conditions) if existing_conditions else "None reported"

    if is_emergency:
        urgency_note = "This includes symptoms that may indicate a medical emergency."
    else:
        urgency_note = "These symptoms do not appear to indicate an immediate emergency."

    conditions_note = f"The patient has the following existing medical conditions: {conditions_text}." if existing_conditions else "The patient has no reported existing medical conditions."

    prompt = f"""You are a healthcare information assistant, not a doctor.
A {age}-year-old {gender} reported these symptoms for {duration}: {symptoms_text}.
{conditions_note}
A machine learning model predicted: {predicted_disease} (confidence: {confidence:.1f}%).
{urgency_note}

Write a short, clear response (under 100 words, plain text, no markdown headers) that:
1. Briefly explains why these symptoms might relate to this condition, factoring in age, gender, symptom duration, and any existing conditions if relevant (e.g. diabetes affecting wound healing, asthma affecting breathlessness risk)
2. Gives 2-3 short practical recommendations as a simple list using a dash
3. If urgent, say to seek immediate medical attention

Use cautious language like "may suggest" or "could indicate". Do not diagnose definitively."""

    response = gemini_model.generate_content(prompt)
    explanation = response.text.strip()

    bar = confidence_bar_html(confidence)

    emergency_html = ""
    if is_emergency:
        emergency_html = """
        <div style='background:linear-gradient(135deg,#DC2626,#991B1B); color:white; padding:16px 20px;
                    border-radius:14px; margin-top:16px; font-weight:600;'>
            🚨 Seek Immediate Medical Attention — some selected symptoms may indicate a medical emergency.
        </div>"""

    result_html = f"""
    <div style='background:white; border-radius:20px; padding:0; overflow:hidden;
                box-shadow:0 8px 30px rgba(15,118,110,0.10); border:1px solid #E2E8F0;'>

        <div style='background:linear-gradient(135deg,#0F766E,#14B8A6); padding:20px 24px; color:white;'>
            <div style='font-size:0.85rem; opacity:0.9; margin-bottom:4px;'>POSSIBLE CONDITION</div>
            <div style='font-size:1.5rem; font-weight:700;'>{predicted_disease}</div>
            <div style='font-size:0.8rem; opacity:0.85; margin-top:6px;'>{display_name} • {age} years, {gender} • Duration: {duration}</div>
        </div>

        <div style='padding:20px 24px;'>
            <div style='display:flex; justify-content:space-between; align-items:center; margin-bottom:16px;'>
                <div>
                    <div style='font-size:0.8rem; color:#64748B; margin-bottom:4px;'>CONFIDENCE</div>
                    <div style='font-family:monospace; font-size:1.1rem; color:#0F766E; letter-spacing:1px;'>{bar} {confidence:.0f}%</div>
                </div>
                <div style='background:{severity_bg}; color:{severity_color}; padding:8px 16px;
                            border-radius:999px; font-weight:600; font-size:0.9rem; white-space:nowrap;'>
                    {severity_label}
                </div>
            </div>

            <div style='height:1px; background:#E2E8F0; margin:16px 0;'></div>

            <div style='color:#334155; line-height:1.7; font-size:0.97rem;'>
                {explanation}
            </div>

            {emergency_html}

            <div style='margin-top:18px; padding:12px 16px; background:#F8FAFC; border-radius:10px;
                        font-size:0.82rem; color:#64748B; border-left:3px solid #14B8A6;'>
                ⚠️ AI-generated information tool, not a medical diagnosis. Consult a licensed healthcare professional.
            </div>
        </div>
    </div>
    """

    safe_name = "".join(c for c in display_name if c.isalnum()) or "Patient"
    pdf_filename = f"MedAssist_Report_{safe_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    build_pdf_report(display_name, age, gender, duration, conditions_text, symptoms_text,
                      predicted_disease, confidence, severity_label, explanation, pdf_filename)

    return result_html, pdf_filename

custom_css = """
@import url('https://fonts.googleapis.com/css2?family=Lexend:wght@400;500;600;700&family=Source+Sans+3:wght@400;500;600&display=swap');

.gradio-container {
    background: #F8FAFC !important;
    font-family: 'Source Sans 3', sans-serif !important;
}

#header-banner {
    background: linear-gradient(135deg, #0F766E 0%, #134E4A 100%);
    border-radius: 20px;
    padding: 24px 28px;
    margin-bottom: 16px;
    box-shadow: 0 8px 30px rgba(15,118,110,0.15);
}

#header-banner h1 {
    color: white !important;
    font-family: 'Lexend', sans-serif !important;
    font-weight: 700 !important;
    font-size: 1.9rem !important;
    margin-bottom: 4px !important;
}

#header-banner p {
    color: #CCFBF1 !important;
    margin: 0 !important;
    font-size: 0.92rem !important;
}

#symptom-box {
    background: #FFFFFF !important;
    border: 1px solid #E2E8F0 !important;
    border-radius: 20px !important;
    padding: 20px !important;
    box-shadow: 0 8px 30px rgba(15,118,110,0.06) !important;
}

.gr-button-primary, button.primary {
    background: linear-gradient(135deg, #0F766E, #14B8A6) !important;
    border: none !important;
    border-radius: 12px !important;
    font-family: 'Lexend', sans-serif !important;
    font-weight: 600 !important;
    padding: 12px !important;
}

footer {visibility: hidden}
"""

def update_conditions_choices(gender):
    if gender == "Female":
        return gr.update(choices=["Diabetes", "Hypertension", "Asthma", "Heart Disease", "Kidney Disease", "Pregnancy"])
    else:
        return gr.update(choices=["Diabetes", "Hypertension", "Asthma", "Heart Disease", "Kidney Disease"], value=[])


def filter_symptoms(search_text, currently_selected):
    if not search_text:
        return gr.update(choices=symptom_display_choices, value=currently_selected)

    search_lower = search_text.lower()
    filtered = [s for s in symptom_display_choices if search_lower in s.lower()]

    # Keep already-selected symptoms visible even if they don't match the search,
    # so the user doesn't lose their previous selections
    for s in currently_selected:
        if s not in filtered:
            filtered.append(s)

    return gr.update(choices=filtered, value=currently_selected)


with gr.Blocks(css=custom_css, title="MedAssist AI") as app:
    gr.HTML("""
        <div id="header-banner">
            <h1>🩺 MedAssist AI</h1>
            <p>AI-Powered Healthcare Assistant </p>
        </div>
    """)

    gr.Markdown("Enter your details and select the symptoms you're experiencing, then click Get Assessment.")

    with gr.Row():
        name_input = gr.Textbox(label="Patient Name", placeholder="Enter your name")
        age_input = gr.Slider(1, 100, value=25, step=1, label="Age")
        gender_input = gr.Radio(["Male", "Female"], value="Male", label="Gender")
        duration_input = gr.Dropdown(
            ["Less than 1 day", "1-3 days", "4-7 days", "More than a week"],
            value="1-3 days",
            label="Symptom Duration"
        )

    conditions_input = gr.CheckboxGroup(
        choices=["Diabetes", "Hypertension", "Asthma", "Heart Disease", "Kidney Disease"],
        label="Existing Medical Conditions (if any)"
    )

    gender_input.change(fn=update_conditions_choices, inputs=gender_input, outputs=conditions_input)

    submit_btn = gr.Button("🔍 Get Assessment", variant="primary")

    with gr.Row():
        with gr.Column(scale=1):
            search_box = gr.Textbox(
                label="Search Symptoms",
                placeholder="Type to filter (e.g. 'fever', 'pain', 'skin')...",
                elem_id="search-box"
            )

            symptom_input = gr.CheckboxGroup(
                choices=symptom_display_choices,
                label="Select Your Symptoms",
                elem_id="symptom-box"
            )

            search_box.change(
                fn=filter_symptoms,
                inputs=[search_box, symptom_input],
                outputs=symptom_input
            )

        with gr.Column(scale=1):
            output_html = gr.HTML(
                value="""<div style='text-align:center; padding:40px; color:#94A3B8;'>
                <div style='font-size:48px; margin-bottom:12px;'>🩺</div>
                <p style='font-size:1.1rem;'>Select your symptoms to get started</p>
                </div>"""
            )
            download_file = gr.File(label="📄 Download PDF Report", visible=True)

    submit_btn.click(
        fn=predict_disease_v5,
        inputs=[name_input, age_input, gender_input, duration_input, conditions_input, symptom_input],
        outputs=[output_html, download_file]
    )

    gr.Markdown("*This tool uses a machine learning model trained on symptom-disease patterns combined with AI-generated explanations. Always consult a licensed healthcare professional for diagnosis and treatment.*")

app.launch(share=True, debug=True)